import { Room } from "@/types";

export const rooms: Room[] = [
  {
    number: 611,
    image: "/images/laboratorium/ruang-lab-611.webp",
    description:
      "Lab ini biasa digunakan untuk mata kuliah Jaringan Komputer dan Cloud Computing.",
    location: "Lantai 6, Gedung A",
    facility: [
      "Kursi Dosen",
      "Kursi mahasiswa",
      "Lemari inventaris",
      "Stop kontak",
      "Kabel UTP",
      "Papan tulis",
      "AC Central",
      "Proyektor",
      "Rak sepatu",
    ],
    summary:
      "Ini adalah ruangan laboratorium komputer 611 yang dirancang dengan konsep fungsional dan terorganisir. Ruangan ini didominasi oleh meja panjang berwarna putih mengkilap yang dilengkapi dengan jalur kabel serta deretan stopkontak di sepanjang permukaannya, menunjukkan kesiapannya untuk penggunaan perangkat elektronik dalam jumlah banyak. Di bawah meja, tersusun rapi sejumlah kursi bulat tanpa sandaran (stool) kayu berwarna gelap yang hemat tempat.",
    regulation: [
      "HARUS menggunakan almamater bagi mahasiswa.",
      "Dilarang membawa, memindahkan, mengubah, atau merusak fasilitas yang ada di lab.",
      "Dilarang makan dan minum di dalam laboratorium.",
      "Dilarang merokok di dalam laboratorium.",
      "Dilarang membawa barang berbahaya ke dalam laboratorium.",
      "Pastikan untuk menjaga kebersihan dan kerapian area kerja di laboratorium.",
      "Dilarang membuat keributan agar tidak mengganggu pengguna laboratorium lainnya.",
      "Setiap mahasiswa bertanggung jawab atas peralatan yang digunakan selama praktikum.",
    ],
    photos: [
      "/images/laboratorium/611/lab_611-1.webp",
      "/images/laboratorium/611/lab_611-2.webp",
      "/images/laboratorium/611/lab_611-3.webp",
      "/images/laboratorium/611/lab_611-4.webp",
      "/images/laboratorium/611/lab_611-5.webp",
    ],
  },
  {
    number: 612,
    image: "/images/laboratorium/ruang-lab-612.webp",
    description:
      "Lab ini biasa digunakan untuk mata kuliah Jaringan Komputer dan Cloud Computing.",
    location: "Lantai 6, Gedung A",
    facility: [
      "Kursi Dosen",
      "Kursi mahasiswa",
      "Lemari inventaris",
      "Stop kontak",
      "Kabel UTP",
      "Papan tulis",
      "AC Central",
      "Proyektor",
      "Rak sepatu",
    ],
    summary:
      "Ini adalah ruangan laboratorium komputer 612 yang memiliki kesamaan seperti ruang laboratorium 611. Ruangan ini didominasi oleh meja panjang berwarna putih mengkilap yang dilengkapi dengan jalur kabel serta deretan stopkontak di sepanjang permukaannya, menunjukkan kesiapannya untuk penggunaan perangkat elektronik dalam jumlah banyak. Di bawah meja, tersusun rapi sejumlah kursi bulat tanpa sandaran (stool) kayu berwarna gelap yang hemat tempat.",
    regulation: [
      "HARUS menggunakan almamater bagi mahasiswa.",
      "Dilarang membawa, memindahkan, mengubah, atau merusak fasilitas yang ada di lab.",
      "Dilarang makan dan minum di dalam laboratorium.",
      "Dilarang merokok di dalam laboratorium.",
      "Dilarang membawa barang berbahaya ke dalam laboratorium.",
      "Pastikan untuk menjaga kebersihan dan kerapian area kerja di laboratorium.",
      "Dilarang membuat keributan agar tidak mengganggu pengguna laboratorium lainnya.",
      "Setiap mahasiswa bertanggung jawab atas peralatan yang digunakan selama praktikum.",
    ],
    photos: [
      "/images/laboratorium/612/lab_612-1.webp",
      "/images/laboratorium/612/lab_612-2.webp",
      "/images/laboratorium/612/lab_612-3.webp",
      "/images/laboratorium/612/lab_612-4.webp",
    ],
  },
  {
    number: 773,
    image: "/images/laboratorium/ruang-lab-773.webp",
    description:
      "Lab ini biasa digunakan untuk mata kuliah Jaringan Komputer dan Cloud Computing.",
    location: "Lantai 8, Gedung C",
    facility: [
      "Kursi Dosen",
      "Kursi mahasiswa",
      "Stop kontak",
      "Kabel UTP",
      "AC",
      "Proyektor",
      "Rak sepatu",
    ],
    summary: "Ini adalah ruang laboratorium komputer 773 yang biasa digunakan untuk praktikum jaringan komputer. Ruangan ini dilengkapi dengan beberapa deretan meja panjang berwarna krem yang disusun sejajar, masing-masing dipasangkan dengan kursi sandaran berwarna hijau toska. Ruang Lab 773 ini berbeda seperti ruang lab lantai 8 lainnya karena tidak difasilitasi komputer.",
    regulation: [
      "HARUS menggunakan almamater bagi mahasiswa.",
      "Dilarang membawa, memindahkan, mengubah, atau merusak fasilitas yang ada di lab.",
      "Dilarang makan dan minum di dalam laboratorium.",
      "Dilarang merokok di dalam laboratorium.",
      "Dilarang membawa barang berbahaya ke dalam laboratorium.",
      "Pastikan untuk menjaga kebersihan dan kerapian area kerja di laboratorium.",
      "Dilarang membuat keributan agar tidak mengganggu pengguna laboratorium lainnya.",
      "Setiap mahasiswa bertanggung jawab atas peralatan yang digunakan selama praktikum.",
    ],
    photos: [
      "/images/laboratorium/773/lab_773-1.webp",
      "/images/laboratorium/773/lab_773-2.webp",
    ],
  },
  {
    number: 775,
    image: "/images/laboratorium/ruang-lab-775.webp",
    description:
      "Lab ini biasa digunakan untuk mata kuliah Mobile Programming, Pemrograman.",
    location: "Lantai 8, Gedung C",
    facility: [
      "Setup (PC, Monitor, Keyboard, Mouse, Meja, Kursi, Headset dan Stop kontak) untuk Dosen dan Mahasiswa",
      "Papan tulis",
      "AC",
      "Rak sepatu",
      "Stop kontak",
      "Proyektor",
    ],
    summary: "Ini adalah ruangan laboratorium komputer 775 yang digunakan untuk mendukung kegiatan praktikum mandiri maupun ujian berbasis komputer. Ruangan ini memiliki tata letak yang sangat teratur dengan deretan bilik komputer individu (cubicle) yang dilengkapi dengan unit PC, monitor, serta headset di setiap mejanya.",
    regulation: [
      "HARUS menggunakan almamater bagi mahasiswa.",
      "Dilarang membawa, memindahkan, mengubah, atau merusak fasilitas yang ada di lab.",
      "Dilarang makan dan minum di dalam laboratorium.",
      "Dilarang merokok di dalam laboratorium.",
      "Dilarang membawa barang berbahaya ke dalam laboratorium.",
      "Pastikan untuk menjaga kebersihan dan kerapian area kerja di laboratorium.",
      "Dilarang membuat keributan agar tidak mengganggu pengguna laboratorium lainnya.",
      "Setiap mahasiswa bertanggung jawab atas peralatan yang digunakan selama praktikum.",
    ],
    photos: [
      "/images/laboratorium/775/lab_775-1.webp",
      "/images/laboratorium/775/lab_775-2.webp",
      "/images/laboratorium/775/lab_775-3.webp",
      "/images/laboratorium/775/lab_775-4.webp",
      "/images/laboratorium/775/lab_775-5.webp",
    ],
  },
  {
    number: 776,
    image: "/images/laboratorium/ruang-lab-776.webp",
    description:
      "Lab ini biasa digunakan untuk mata kuliah Mobile Programming, Pemrograman.",
    location: "Lantai 8, Gedung C",
    facility: [
      "Setup (PC, Monitor, Keyboard, Mouse, Meja, Kursi, Headset dan Stop kontak) untuk Dosen dan Mahasiswa",
      "Papan tulis",
      "AC",
      "Rak sepatu",
      "Stop kontak",
      "Proyektor",
    ],
    summary:
      "Ini adalah ruangan laboratorium komputer 776 yang memili kemiripan dengan ruang lab 775. Lab ini biasa digunakan untuk mendukung kegiatan praktikum mandiri maupun ujian berbasis komputer. Ruangan ini memiliki tata letak yang sangat teratur dengan deretan bilik komputer individu (cubicle) yang dilengkapi dengan unit PC, monitor, serta headset di setiap mejanya.",
    regulation: [
      "HARUS menggunakan almamater bagi mahasiswa.",
      "Dilarang membawa, memindahkan, mengubah, atau merusak fasilitas yang ada di lab.",
      "Dilarang makan dan minum di dalam laboratorium.",
      "Dilarang merokok di dalam laboratorium.",
      "Dilarang membawa barang berbahaya ke dalam laboratorium.",
      "Pastikan untuk menjaga kebersihan dan kerapian area kerja di laboratorium.",
      "Dilarang membuat keributan agar tidak mengganggu pengguna laboratorium lainnya.",
      "Setiap mahasiswa bertanggung jawab atas peralatan yang digunakan selama praktikum.",
    ],
    photos: [
      "/images/laboratorium/776/lab_776-1.webp",
      "/images/laboratorium/776/lab_776-2.webp",
      "/images/laboratorium/776/lab_776-3.webp",
      "/images/laboratorium/776/lab_776-4.webp",
      "/images/laboratorium/776/lab_776-5.webp",
    ],
  },
  {
    number: 782,
    image: "/images/laboratorium/ruang-lab-782.webp",
    description:
      "Lab ini biasa digunakan untuk mata kuliah Basis Data, Algorithma dan Pemrograman, dan Data Mining.",
    location: "Lantai 8, Gedung C",
    facility: [
      "Setup (PC, Monitor, Keyboard, Mouse, Meja, Kursi, Headset dan Stop kontak) untuk Dosen dan Mahasiswa",
      "Papan tulis",
      "AC",
      "Rak sepatu",
      "Stop kontak",
      "Proyektor",
    ],
    summary: "Ini adalah ruangan laboratorium komputer 782 yang digunakan untuk ujian atau praktikum. Ruangan ini memiliki tata letak yang sangat teratur dengan deretan bilik (cubicle) individu berwarna putih yang dilengkapi dengan monitor, unit PC, serta headset yang tergantung rapi di setiap posisinya.",
    regulation: [
      "HARUS menggunakan almamater bagi mahasiswa.",
      "Dilarang membawa, memindahkan, mengubah, atau merusak fasilitas yang ada di lab.",
      "Dilarang makan dan minum di dalam laboratorium.",
      "Dilarang merokok di dalam laboratorium.",
      "Dilarang membawa barang berbahaya ke dalam laboratorium.",
      "Pastikan untuk menjaga kebersihan dan kerapian area kerja di laboratorium.",
      "Dilarang membuat keributan agar tidak mengganggu pengguna laboratorium lainnya.",
      "Setiap mahasiswa bertanggung jawab atas peralatan yang digunakan selama praktikum.",
    ],
    photos: [
      "/images/laboratorium/782/lab_782-1.webp",
      "/images/laboratorium/782/lab_782-2.webp",
    ],
  },
];
