import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ASLAB TI - Universitas Pamulang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" className="scroll-smooth overflow-y-auto" suppressHydrationWarning>
      <body
        className={cn(geistSans.variable, geistMono.variable, "font-sans antialiased w-full bg-base-50 overflow-x-hidden")}
      >
        <main id="main" className="w-full bg-transparent min-w-1 max-w-none">
          {children}
        </main>
      </body>
    </html>
  );
}
